### ISSUE TITLE
Add work item options

### ISSUE THREAD

**Issue by MPDFO** [joachimdalen/azdevops-auto-state#44]
Hello there,

I was looking for some time for an extension to automatically update the status of an item. Thank you for making this module!

It would be interesting to add a possibility to filter the items impacted by the rules.

For example:
A Task with specific field (Tags: "xx", "activity" xx) would trigger the auto status and not all tasks.
Same for the target item, the use of a filter could help.
Like the clauses for queries.

could you look into this ?
Thank you

**Comment by joachimdalen** [comment]
Hi!

I have actually gone a bit back and forth on this feature, but figured I might wait until someone asked for it. The way the rule check engine is built, it should not be too much work... I think.

I will take a look into this and see what is possible.

**Comment by joachimdalen** [comment]
I've done some minor experiments, and it looks like this is possible to get up with a bit of work. I'm adding it to the backlog and working on it further :)

**Comment by joachimdalen** [comment]
Hi again,

I am currently implementing this and wanted to check in to see that it is moving in the correct direction. Version 1 of this feature will allow you to dynamically select fields (both custom and pre defined) that is one of the types:

- Boolean
- Identity
- Integer
- PlainText
- String

Based on the value type, you will be able to select one of the following compare operations:
- `= (Equals)`
- `<> (Not Equals)`
- `> (Greater Than)`
- `< (Less Than)`
- `>= (Greater Than Equals)`
- `<= (Less Than Equals)`

Some fields will give you custom controls to manage the compare value better (such as a tag picker and identity picker). 

Is this like you were thinking?

Currently how the UI is:
![image](https://user-images.githubusercontent.com/15696189/168486525-a804376f-f4ef-4bb6-9b45-bea98ec9484f.png)

**Comment by MPDFO** [comment]
It looks promising !

To select the field, will we have to use the "Reference name" or the "field name"? I m still novice on devops and dunno all the references names I will need yet.

**Comment by joachimdalen** [comment]
It uses and stores the ReferenceName since this is a unique field. When you are creating/updating the filters, you will be presented with a dropdown over all the supported fields. This uses the field name to make it easier: 

<img width="536" alt="image" src="https://user-images.githubusercontent.com/15696189/168614805-38a7ed2a-dbb0-4ddf-9afd-56afac57f5b0.png">

**Comment by joachimdalen** [comment]
This feature suddenly became a bit bigger than expected, so it might take a bit longer. I am currently facing some issues in figuring out how the new filter functionality should integrate with the two options of `Children lookup` and `Process parent`.

Currently you are only allowed to create unique rules based on the selection of Work Item types (Child and parent) and the source/target state. This works fine with this issues when dynamically resolving the parent/child rules in the background, but when introducing filter I feel like we should have the option of being able to duplicate rules where only the filter is the difference.

This means that the background processing might receive two rules when resolving for child/parent, and it does not know which to pick for further processing.

Currently the filters you add does `AND` when comparing, but I might need to add "rule groups" to this. That means we avoid the issue of duplicate rules, and you can define sets of filters that belongs together.

**Comment by MPDFO** [comment]
Ok.

We dont currently use the feature Children lookup and Process parent. And we look forward to testing your work on automating status changes.

**Comment by joachimdalen** [comment]
Hi! 

I do not have a set EAT for the release yet as it is taking a bit longer to figure out the issues. With the current progress maybe this upcoming weekend or sometime next week.

**Comment by joachimdalen** [comment]
I am going into a validation and testing step now. The main features should be done, but it might take some more time if issues are found during testing :smile:

**Comment by joachimdalen** [comment]
Will aim for release next weekend, still need to do some tests, fix some minor issues and write the documentation for it.

**Comment by MPDFO** [comment]
Good to hear. I m looking forward to test it !

**Comment by MPDFO** [comment]
Good to hear. I m looking forward to test it !

**Comment by joachimdalen** [comment]
This is now merged. I have a few smaller changes that is also included in the next release. Once all changes are implemented and nothing appears in a manual test this will be released.

**Comment by joachimdalen** [comment]
This just released in `v1.3.0`. You can read some of the docs [here](https://devops-extensions.dev/docs/extensions/auto-state/rules/filters), please let me know if you have any issues.

**Comment by MPDFO** [comment]
Thank you for your work, i m going to try it right now!

**Comment by MPDFO** [comment]
First of all, thank you for the update. It works pretty well.

Here a first feedback on setting the extension:
**Menu**
- It would be interesting to be able to set a title for the rule
- Then a possibility to sort the rules
**Same state but different filters**
- I have a error message when i set same condition for same type of item (ex task) but with different filter (ex task "specification" and task "developpement") I want the same parent target state for both of these tasks, in this case "dev in progress" but a message "A rule already exists that matches the current configuration" (I could manage it if I create new states but could be more confusing)
![image](https://user-images.githubusercontent.com/105295700/172143808-249df47b-c456-4cb7-b9c4-1c511ac2cc98.png)
here an example of our backlog for customdev (yellow arrow = in progress, green = done for task state)
**Child look up**
- I ve tried to set this option. For example in my project we have different code part for a same developpment. I would like when all my tasks with the filter "dev" reach the state "done", the parent state change to "dev completed". May be i m mistaking in the setting
**State update**
- The auto state works only when you change state from the item page, but not from the backlog page (using right clic, then edit) Is there any tech reason for that?

**Comment by joachimdalen** [comment]
Hi!

Thank you for the feedback, I'll address some of it here.

1. The limitation that triggers the message  "A rule already exists that matches the current configuration" is a technical limitation due to `Parent processing` and `Children lookup`. If the only thing that is different between the two rules is the filters, then you can add another filter group. This is the reason filters are grouped this way. This is also described in the documentation [here](https://devops-extensions.dev/docs/extensions/auto-state/rules/filters). A rule will be considered matched when `Main option + at least one filter group` matches.

2. Children lookup has some requirements:
- The parent work item must have a rule for the same state. If the state is different between child/parent, this option will not match.
- When checking children, a rule must be defined for each work item type and the state must match the one of the parent.

I am currently looking into improving this option, but it currently does not work very well if you have custom states that is different between the child and parent.

Take the following rule configuration:
![image](https://user-images.githubusercontent.com/15696189/172146954-0f785cca-6e65-473f-a14e-6f0fdb589bbe.png)

This would close the `User Story` when the last `Task` below it is closed AND all the other tasks are closed. When it is checking children, it looks for any rules that targets the same state (Parent target state) and checks that all the work items are in this state.

3. The state update will only trigger from the work item form and the backlog view for a single work item. Not mass updates. This issue is the same as for: https://github.com/joachimdalen/azdevops-auto-state/issues/38#issuecomment-1049943447

When it comes to titles and sorting I am a bit more unsure. I am currently looking into if the rule editor should be redesigned (maybe a bit more like the default interface for Work item templates), but I'll keep those wishes in the back of my head when looking into that.

**Comment by MPDFO** [comment]
Hi there here a little more feedback:

I ve read that the change of state only works when changing state in the form of the item. i can confirm that. I ve tried mass edit, drag and drop and from the "panel form" in query result, the auto state doesnt work. We really have to enter in the form/page of the item.

**Comment by joachimdalen** [comment]
Thank you for the additional feedback. :smile: 
I am currently on holiday,  but have created a new issue from your feedback and will follow up when I am back.
