### ISSUE TITLE
Child Look Up feature is not working correctly

### ISSUE THREAD

**Issue by indiadixon** [joachimdalen/azdevops-auto-state#58]
**Describe the bug**
I have a Child Look Up turned on for two rules, when User Story = Closed > Feature = Quality Demo, and when Test Scope = Completed > Feature = Quality Demo. However, when both the User Story and the Test Scope move to Closed/Completed, the Feature isn't moving to Quality Demo.

**Expected behavior**
When both children (User Story and Test Scope) reach their transition state, the parent (feature) will move to its target state (Quality Demo) because Child Look Up is turned on for both the User Story and Test Scope Rules.

**Comment by joachimdalen** [comment]
Hi, thank you for reporting.

I need some additional information to debug this further. I created a similar setup on my side, and seem to work fine here using a structure of:
![image](https://user-images.githubusercontent.com/15696189/179170292-b077bdf1-cf94-4922-8319-8ab6832a4737.png)

1. From what view are you updating the work items? Due to limitations in Azure DevOps the state **must** be updated from the work item form.
2. How does the rest of the work item tree look under that feature? When using child lookup, there must be rules for every work item type that matches the target state of the parent.

**Comment by indiadixon** [comment]
Hi, I tried to go in myself and recreate the bug, but it's working now! Thanks!

**Comment by joachimdalen** [comment]
Great!  Glad you got it working.

When I think about it, you might have had a mismatch in the rule state. This can happen if you create/update rules in one tab, and already have the backlog/workitem open in a different tab. 

It might not have loaded the latest changes to the rules and therefor not applied them correctly. I'll see if this can be improved and add a note about it in the docs.

**Comment by indiadixon** [comment]
Actually I think this is exactly what happened, I was inputting rules in one tab, and then had a query open in another to test if they were working. This morning when I saw your response, I tried it again and it worked perfectly
