### ISSUE TITLE
Task state update does not update the User Story

### ISSUE THREAD

**Issue by Tester1713** [joachimdalen/azdevops-auto-state#69]
**Describe the bug**
I have 4 tasks under a user story and 2 of them are closed, 1 is new and 1 is active. But the parent User Story is still not updating into Active. 
I already tried adding the children look up in the app but it still doesn't work,

When I use the Rule Tester, it shows the correct result but it does not reflect in the work items. I am viewing the items in the Sprint backlog view if that helps.  

**To Reproduce**
Create a User Story and add 4 tasks under it. (2 close, 1 new and 1 active)

**Expected behavior**
I am expecting that the user story should be change state into Active

**What version are you on:**
Version 1.3.0

**Additional context**
You can also see that the Feature Parent is also not being updated based on the rule tester. 

I attached the image from my testing and the rule setup: 
![Auto State Issue](https://user-images.githubusercontent.com/113021020/188847214-c0fa8d87-351f-48fb-a984-b4cefc24ee7a.png)

**Comment by joachimdalen** [comment]
Hi there, sorry for the delay in response!

When you are changing the task state from `New` -> `Active`, in which way are you doing this? Drag/Drop, from the work item edit form etc

Unfortunately there are limited places where the extension is able to hook into the change event of a work item, so your way of updating might not trigger the extension.

**Comment by Tester1713** [comment]
Hi, we update the tasks usually by selecting the State from the dropdown. Sometimes we also use the taskboard from the Azure Devops under the Sprint tab. What resolution can you recommend to solve this issue? we really wanted to have this app working since we have thousands of work items and its difficult to update each one of them.

**Comment by joachimdalen** [comment]
Hi,

Considering the Rule Tester is showing the correct result, it means that the update event has not been triggered when the state changed for the work item.

Due to certain technical limitations in Azure DevOps, this event is only fired in a few places where the extension is able to pick it up. 

The best way is to update the work item from the work item from/card as it should always trigger there. I know for a fact that the event is not triggered when dragging work items between columns in the task board, but there isn't much I can do about that until DevOps fires the update event there.

There is a limitation in the extension that if you update a rule, you mush refresh the window before updating a work item for the rules to apply. I am working on making this more seamless.

**Comment by joachimdalen** [comment]
Hi!

I'm going to close this due to the lack of a response. Please fell free to update if it's still an issue.
